"use client";

import { useMemo, useState } from "react";

type CallKey = "out" | "reach" | "goal";
const calls: Record<CallKey, { current: string; recommended: string; confidence: string; rationale: string; action: string }> = {
  out: { current: "Out of bounds — Brooklyn possession", recommended: "Out of bounds — opponent possession", confidence: "91%", rationale: "Baseline and sideline views show the ball contacting Brooklyn #8 after the deflection.", action: "Challenge" },
  reach: { current: "Reach-in foul — Brooklyn", recommended: "No foul — legal defensive contact", confidence: "84%", rationale: "Contact occurs after the ball is dislodged; the defender’s hand contacts the ball first.", action: "Challenge" },
  goal: { current: "Goaltending — Brooklyn", recommended: "Legal block — no goaltending", confidence: "88%", rationale: "Ball is rising at the point of contact and remains below the cylinder plane.", action: "Challenge" },
};

const cameras = ["Baseline left", "Baseline right", "Sideline A", "Sideline B", "High center", "Rim camera"];

export function ChallengeAssist() {
  const [call, setCall] = useState<CallKey>("out");
  const [frame, setFrame] = useState(12);
  const [analyzing, setAnalyzing] = useState(false);
  const verdict = useMemo(() => calls[call], [call]);
  function runAnalysis() { setAnalyzing(true); let next = 0; const timer = window.setInterval(() => { next += 1; setFrame((value) => (value + 7) % 48); if (next === 7) { window.clearInterval(timer); setAnalyzing(false); } }, 180); }
  return <main className="mx-auto max-w-[1460px] px-5 py-7 md:px-8 lg:px-10"><section className="border border-white/10 bg-[#121212] p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/45">Challenge Assist</p></div><label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.16em] text-white/45">Current call</span><select value={call} onChange={(event) => setCall(event.target.value as CallKey)} className="rounded-lg border border-white/15 bg-[#0b0b0b] px-3 py-3 text-sm font-bold text-white outline-none focus:border-[#e84b37]"><option value="out">Out of bounds — Brooklyn</option><option value="reach">Reach-in foul — Brooklyn</option><option value="goal">Goaltending — Brooklyn</option></select></label></div><div className="mt-5 border-l-4 border-[#e84b37] bg-[#e84b37]/10 px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/50">On-court ruling</p><p className="mt-1 text-xl font-black">{verdict.current}</p></div></section><section className="mt-7 grid gap-7 xl:grid-cols-[1fr_340px]"><div><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-black uppercase tracking-[.12em]">Synchronized camera wall</h2><p className="mt-1 text-xs text-white/45">Frame {frame + 1} of 48 · multi-angle replay mock</p></div><button onClick={runAnalysis} disabled={analyzing} className="rounded-sm bg-[#e84b37] px-4 py-3 text-xs font-black uppercase tracking-[.12em] text-white transition hover:bg-[#f35c48] disabled:opacity-60">{analyzing ? "Analyzing…" : "Run automated analysis"}</button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{cameras.map((camera, index) => <Camera key={camera} name={camera} frame={frame} index={index} />)}</div></div><aside className="border border-white/10 bg-[#121212] p-5"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/45">Automated review</p><p className="mt-4 text-3xl font-black tracking-[-.06em]">{verdict.action}</p><p className="mt-1 text-sm text-[#e84b37]">{verdict.confidence} confidence</p><div className="mt-5 border-y border-white/10 py-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-white/45">Recommended ruling</p><p className="mt-2 text-base font-bold">{verdict.recommended}</p></div><p className="mt-5 text-sm leading-6 text-white/65">{verdict.rationale}</p><div className="mt-6 space-y-3 text-xs"><div className="flex justify-between"><span className="text-white/45">Camera agreement</span><b>5 / 6 views</b></div><div className="flex justify-between"><span className="text-white/45">Review window</span><b>01.8 sec</b></div><div className="flex justify-between"><span className="text-white/45">Time remaining</span><b>01:14</b></div></div></aside></section></main>;
}

function Camera({ name, frame, index }: { name: string; frame: number; index: number }) { const ballX = 26 + ((frame * (index + 2)) % 50); const ballY = 34 + ((frame * (index + 1)) % 24); return <article className="overflow-hidden border border-white/10 bg-[#111]"><div className="relative aspect-video overflow-hidden bg-[radial-gradient(circle_at_50%_35%,#6c5b45_0,transparent_18%),linear-gradient(145deg,#251f1a,#0a0a0a_70%)]"><div className="absolute inset-x-5 bottom-4 top-4 border border-[#e6d5a6]/35" /><div className="absolute left-1/2 top-4 h-[calc(100%-2rem)] border-l border-[#e6d5a6]/25" /><div className="absolute left-[20%] right-[20%] top-1/2 border-t border-[#e6d5a6]/25" /><div className="absolute h-3 w-3 rounded-full bg-[#e84b37] shadow-[0_0_12px_#e84b37]" style={{ left: `${ballX}%`, top: `${ballY}%` }} /><div className="absolute bottom-3 left-3 bg-black/70 px-2 py-1 font-mono text-[10px] text-white/70">CAM {index + 1} · {String(frame + 1).padStart(2, "0")}</div></div><p className="border-t border-white/10 px-3 py-2 text-xs font-bold text-white/70">{name}</p></article>; }
