"use client";

import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Radar, RadarChart, ResponsiveContainer, Tooltip, PolarAngleAxis, PolarGrid, XAxis } from "recharts";

type Props = { detail: any; context: any };
const money = (n: number | null | undefined) => n == null ? "—" : `$${(n / 1_000_000).toFixed(1)}M`;
const num = (n: number | null | undefined, digits = 1) => n == null ? "—" : n.toFixed(digits);

export function DecisionDashboard({ detail, context }: Props) {
  const { player, advanced_season: season, advanced_history: history, contract, contract_years: years, shooting_zones: zones } = detail;
  const darko = detail.darko; const team = context?.team_code ?? "BKN";
  const avg = context?.team_averages ?? {};
  const radar = [
    ["PTS", season?.pts, avg.pts], ["AST", season?.ast, avg.ast], ["REB", season?.reb, avg.reb],
    ["eFG%", season?.efg_pct ? season.efg_pct * 30 : 0, avg.efg_pct ? avg.efg_pct * 30 : 0],
    ["NetRtg", (season?.net_rating ?? 0) + 15, (avg.net_rating ?? 0) + 15], ["PIE", (season?.pie ?? 0) * 100, (avg.pie ?? 0) * 100],
  ].map(([metric, playerValue, teamValue]) => ({ metric, player: Number(playerValue ?? 0), team: Number(teamValue ?? 0) }));
  const impact = history.map((row: any) => ({ season: row.season, net: row.net_rating, pie: row.pie == null ? null : row.pie * 100 }));
  const cap = years.map((row: any) => ({ season: row.season, player: row.salary / 1_000_000, team: Math.max(0, (context?.contract_payroll ?? 0) / 1_000_000 - row.salary / 1_000_000), tax: 188, first: 196, second: 207 }));
  return <div className="space-y-7">
    <section className="grid gap-5 xl:grid-cols-[460px_1fr]">
      <article className="border border-white/10 bg-[#121212] p-6"><div className="flex gap-5"><img src={player.headshot_url} alt={player.full_name} className="h-28 w-28 object-cover object-top" /><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/45">Player evaluation</p><h1 className="mt-2 text-4xl font-black tracking-[-.07em]">{player.full_name}</h1><p className="mt-2 text-sm text-white/55">{player.team_name} · {player.position || "—"}</p><p className="mt-1 text-xs text-white/40">{player.height || "—"} · {player.weight || "—"}</p></div></div></article>
      <article className="border border-white/10 bg-[#121212] p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/45">{team} salary-cap snapshot</p><div className="mt-4 grid grid-cols-3 gap-6"><Metric label="Listed payroll" value={money(context?.contract_payroll)} /><Metric label="Player cap hit" value={money(contract?.cap_hit)} /><Metric label="Years remaining" value={contract?.years_remaining ?? "—"} /></div><p className="mt-4 text-xs text-white/45">{contract?.contract_type ?? "No reviewed contract loaded"}{years.some((y: any) => y.player_option) ? " · Player option" : ""}{years.some((y: any) => y.team_option) ? " · Team option" : ""}</p></article>
    </section>
    <Section title="Production" subtitle={`Player profile relative to ${team}`}><div className="grid gap-5 xl:grid-cols-3"><Card title="Team impact"><ResponsiveContainer width="100%" height={290}><RadarChart data={radar}><PolarGrid stroke="#ffffff22" /><PolarAngleAxis dataKey="metric" tick={{ fill: "#ffffff99", fontSize: 11 }} /><Radar name={player.full_name} dataKey="player" stroke="#f4f3ee" fill="#f4f3ee" fillOpacity={.22} /><Radar name={team} dataKey="team" stroke="#e84b37" fill="#e84b37" fillOpacity={.18} /><Legend wrapperStyle={{fontSize:12}} /></RadarChart></ResponsiveContainer></Card><Card title="Impact trajectory" className="xl:col-span-2"><ResponsiveContainer width="100%" height={290}><LineChart data={impact}><CartesianGrid stroke="#ffffff15" vertical={false} /><Tooltip /><Line type="monotone" dataKey="net" stroke="#f4f3ee" strokeWidth={2} name="Net Rating" /><Line type="monotone" dataKey="pie" stroke="#e84b37" strokeWidth={2} name="PIE × 100" /><Legend /><XAxis dataKey="season" tick={{fill:'#ffffff88',fontSize:11}} /></LineChart></ResponsiveContainer></Card></div></Section>
    <Section title="Efficiencies" subtitle="Shooting profile and conversion"><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card title="Shooting zones"><Court zones={zones} /></Card><Card title="Latest season"><div className="grid grid-cols-2 gap-px bg-white/10">{[["TS%", `${num(season?.ts_pct ? season.ts_pct * 100 : null)}%`],["eFG%", `${num(season?.efg_pct ? season.efg_pct * 100 : null)}%`],["ORtg",num(season?.off_rating)],["DRtg",num(season?.def_rating)]].map(([l,v])=><div key={l} className="bg-[#121212] p-5"><p className="text-xs text-white/45">{l}</p><p className="mt-2 text-3xl font-black">{v}</p></div>)}</div><p className="mt-5 text-xs text-white/45">DARKO snapshot: DPM {num(darko?.dpm)} · OFF {num(darko?.off_dpm)} · DEF {num(darko?.def_dpm)}.</p></Card></div></Section>
    <Section title="Salary cap" subtitle="Player salary stacked on selected-team listed payroll"><Card title="Future commitments"><ResponsiveContainer width="100%" height={280}><BarChart data={cap}><CartesianGrid stroke="#ffffff15" vertical={false} /><XAxis dataKey="season" tick={{fill:'#ffffff88',fontSize:11}} /><Tooltip formatter={(v: any) => `$${v.toFixed(1)}M`} /><Legend /><Bar dataKey="team" stackId="a" fill="#555" name={`${team} payroll`} /><Bar dataKey="player" stackId="a" fill="#e84b37" name={`${player.full_name} cap hit`} /></BarChart></ResponsiveContainer><div className="flex gap-5 text-xs text-white/45"><span>Reference: luxury tax $188M</span><span>1st apron $196M</span><span>2nd apron $207M</span></div></Card></Section>
  </div>;
}
function Section({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section><div className="mb-3 flex items-baseline gap-3"><h2 className="text-lg font-black uppercase tracking-[.12em]">{title}</h2><p className="text-xs text-white/45">{subtitle}</p></div>{children}</section>; }
function Card({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <article className={`border border-white/10 bg-[#121212] p-5 ${className}`}><h3 className="text-xs font-bold uppercase tracking-[.12em] text-white/55">{title}</h3><div className="mt-3">{children}</div></article>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><p className="text-xs text-white/45">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>; }
function Court({ zones }: { zones: any[] }) { const values = zones.slice(0, 5); return <div className="relative mx-auto h-80 max-w-xl overflow-hidden bg-[#151515]"><svg viewBox="0 0 500 470" className="absolute inset-0 h-full w-full" aria-label="Basketball half-court shooting zones"><rect x="20" y="15" width="460" height="440" fill="none" stroke="#f4f3ee" strokeWidth="2" opacity=".8" /><line x1="220" y1="45" x2="280" y2="45" stroke="#f4f3ee" strokeWidth="3" /><circle cx="250" cy="68" r="8" fill="none" stroke="#f4f3ee" strokeWidth="2" /><rect x="170" y="15" width="160" height="190" fill="none" stroke="#f4f3ee" strokeWidth="2" /><path d="M190 205a60 60 0 0 1 120 0" fill="none" stroke="#f4f3ee" strokeWidth="2" /><circle cx="250" cy="205" r="60" fill="none" stroke="#f4f3ee" strokeWidth="2" strokeDasharray="4 3" /><path d="M80 15V175A190 190 0 0 0 420 175V15" fill="none" stroke="#f4f3ee" strokeWidth="2" /><path d="M210 68a40 40 0 0 1 80 0" fill="none" stroke="#f4f3ee" strokeWidth="2" /><line x1="20" y1="365" x2="480" y2="365" stroke="#f4f3ee" strokeWidth="2" /></svg>{values.map((z, index) => <div key={z.zone} style={{left:["9%","38%","69%","23%","57%"][index], top:["12%","38%","12%","63%","63%"][index]}} className="absolute grid h-14 w-14 place-items-center rounded-full border border-white/50 bg-[#e84b37]/90 text-center shadow-lg"><b className="text-sm">{num(z.fg_pct * 100)}%</b><small className="px-1 text-[7px] leading-2">{z.zone}</small></div>)}</div>; }
