"use client";

import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Detail = { player: { full_name: string; team_name: string; position: string; height: string | null; weight: string | null; headshot_url: string }; advanced_season: { season: string; gp: number; min: number; off_rating: number; def_rating: number; net_rating: number; usage_pct: number; ts_pct: number; pace: number; pie: number } | null; combine_measurements: Record<string, string | number | null> | null; combine_tests: Record<string, string | number | null> | null };
const stat = (value: number | null, digits = 1) => value == null ? "—" : value.toFixed(digits);

export function PlayerWorkspace() {
  const [player, setPlayer] = useState<Detail | null>(null); const [loading, setLoading] = useState(true);
  async function selectPlayer(slug: string) { setLoading(true); try { const response = await fetch(`${API_URL}/api/v1/ingested-players/${slug}`); setPlayer(response.ok ? await response.json() : null); } finally { setLoading(false); } }
  useEffect(() => { selectPlayer("stephen-curry"); }, []);
  return <AppShell onPlayerSelect={selectPlayer}><main className="mx-auto max-w-[1460px] px-5 py-7 md:px-8 lg:px-10">{loading && <p className="py-24 text-center text-sm text-white/45">Loading NBA data…</p>}{player && <Profile detail={player} />}</main></AppShell>;
}

function Profile({ detail }: { detail: Detail }) { const { player, advanced_season: advanced, combine_measurements: measure, combine_tests: tests } = detail; return <><header className="border border-white/10 bg-[#121212] p-6 md:p-8"><div className="flex items-center gap-6"><img src={player.headshot_url} alt={player.full_name} className="h-32 w-32 object-cover object-top" /><div><img src="/brand/bklyn-nets-city-edition.png" alt="BKL​YN NETS City Edition" className="h-9 w-[78px] object-cover" /><h1 className="mt-4 text-5xl font-black tracking-[-0.075em]">{player.full_name}</h1><p className="mt-2 text-sm text-white/55">{player.team_name} · {player.position || "—"} · {player.height || "—"} · {player.weight || "—"}</p></div></div></header>{advanced && <section className="mt-5 grid gap-px border border-white/10 bg-white/10 md:grid-cols-4">{[["Offensive rating", stat(advanced.off_rating)], ["Defensive rating", stat(advanced.def_rating)], ["Net rating", stat(advanced.net_rating)], ["True shooting", `${stat(advanced.ts_pct * 100)}%`]].map(([label, value]) => <article key={label} className="bg-[#121212] p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-white/45">{label}</p><p className="mt-4 text-3xl font-black">{value}</p><p className="mt-2 text-xs text-white/40">{advanced.season} · {advanced.gp} GP</p></article>)}</section>}<section className="mt-5 grid gap-5 md:grid-cols-2">{measure && <DataCard title="Draft combine measurements" data={measure} fields={["height_wo_shoes", "weight", "wingspan", "standing_reach", "body_fat_pct"]} />}{tests && <DataCard title="Draft combine testing" data={tests} fields={["standing_vertical", "max_vertical", "lane_agility", "three_quarter_sprint", "bench_press"]} />}</section></>; }
function DataCard({ title, data, fields }: { title: string; data: Record<string, string | number | null>; fields: string[] }) { const label = (key: string) => key.replaceAll("_", " "); return <article className="border border-white/10 bg-[#121212] p-6"><h2 className="text-sm font-black uppercase tracking-[0.12em]">{title}</h2><dl className="mt-5 space-y-3">{fields.map((field) => <div key={field} className="flex justify-between border-b border-white/10 pb-2 text-sm"><dt className="capitalize text-white/45">{label(field)}</dt><dd className="font-bold">{data[field] ?? "—"}</dd></div>)}</dl></article>; }
