"use client";

import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { TrendChart } from "@/components/trend-chart";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Advanced = { season: string; gp: number; min: number; off_rating: number; def_rating: number; net_rating: number; usage_pct: number; ts_pct: number; pace: number; pie: number };
type Detail = { player: { slug: string; full_name: string; team_name: string; position: string; height: string | null; weight: string | null; headshot_url: string }; advanced_season: Advanced | null; advanced_history: Advanced[]; similar_players: { slug: string; name: string; team: string; distance: number }[]; shooting_zones: { zone: string; fga: number; fgm: number; fg_pct: number }[]; combine_measurements: Record<string, string | number | null> | null; combine_tests: Record<string, string | number | null> | null; contract: { contract_type: string; current_salary: number | null; cap_hit: number | null; years_remaining: number | null; as_of_date: string; source: string } | null; contract_years: { season: string; salary: number | null; player_option: number; team_option: number; early_termination_option: number }[] };
const stat = (value: number | null, digits = 1) => value == null ? "—" : value.toFixed(digits);

export function PlayerWorkspace() {
  const [player, setPlayer] = useState<Detail | null>(null); const [loading, setLoading] = useState(true); const [team, setTeam] = useState("BKN"); const [context, setContext] = useState<{ team_code: string; season: string; roster_count: number; team_averages: Record<string, number | null>; player_delta: Record<string, number> | null; contract_payroll: number; contracted_players: number } | null>(null);
  async function selectPlayer(slug: string) { setLoading(true); try { const response = await fetch(`${API_URL}/api/v1/ingested-players/${slug}`); setPlayer(response.ok ? await response.json() : null); } finally { setLoading(false); } }
  useEffect(() => { selectPlayer("stephen-curry"); }, []);
  useEffect(() => { if (player) fetch(`${API_URL}/api/v1/team-context/${team}?player_slug=${player.player.slug}`).then((r) => r.ok ? r.json() : null).then(setContext).catch(() => setContext(null)); }, [team, player]);
  return <AppShell onPlayerSelect={selectPlayer} team={team} onTeamChange={setTeam}><main className="mx-auto max-w-[1460px] px-5 py-7 md:px-8 lg:px-10">{loading && <p className="py-24 text-center text-sm text-white/45">Loading NBA data…</p>}{player && <>{context && <TeamContext context={context} />}<Profile detail={player} onSelect={selectPlayer} /></>}</main></AppShell>;
}

function TeamContext({ context }: { context: NonNullable<PlayerWorkspaceContext> }) { const money = `$${(context.contract_payroll / 1_000_000).toFixed(1)}M`; const delta = context.player_delta?.net_rating; return <section className="mb-5 border border-white/10 bg-[#121212] p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-white/45">Selected team context</p><h2 className="mt-1 text-xl font-black">{context.team_code} · {context.season}</h2></div><p className="text-sm text-white/60">{context.roster_count} rostered players · {context.contracted_players} contract records · {money} listed payroll</p></div><div className="mt-4 flex gap-6 text-xs text-white/55"><span>Team avg NetRtg: <b className="text-white">{context.team_averages.net_rating?.toFixed(1) ?? "—"}</b></span><span>Selected player delta: <b className="text-white">{delta == null ? "—" : `${delta > 0 ? "+" : ""}${delta.toFixed(1)}`}</b></span></div></section>; }
type PlayerWorkspaceContext = { team_code: string; season: string; roster_count: number; team_averages: Record<string, number | null>; player_delta: Record<string, number> | null; contract_payroll: number; contracted_players: number } | null;

function Profile({ detail, onSelect }: { detail: Detail; onSelect: (slug: string) => void }) { const { player, advanced_season: advanced, combine_measurements: measure, combine_tests: tests } = detail; const trends = detail.advanced_history.map((row) => ({ season: row.season, points: row.off_rating, true_shooting: row.ts_pct * 100, usage: row.usage_pct * 100, minutes: row.min })); const money = (value: number | null) => value == null ? "—" : `$${(value / 1_000_000).toFixed(1)}M`; return <><header className="border border-white/10 bg-[#121212] p-6 md:p-8"><div className="flex items-center gap-6"><img src={player.headshot_url} alt={player.full_name} className="h-32 w-32 object-cover object-top" /><div><img src="/brand/bklyn-nets-city-edition.png" alt="BKL​YN NETS City Edition" className="h-9 w-[78px] object-cover" /><h1 className="mt-4 text-5xl font-black tracking-[-0.075em]">{player.full_name}</h1><p className="mt-2 text-sm text-white/55">{player.team_name} · {player.position || "—"} · {player.height || "—"} · {player.weight || "—"}</p></div></div></header>{advanced && <section className="mt-5 grid gap-px border border-white/10 bg-white/10 md:grid-cols-4">{[["Offensive rating", stat(advanced.off_rating)], ["Defensive rating", stat(advanced.def_rating)], ["Net rating", stat(advanced.net_rating)], ["True shooting", `${stat(advanced.ts_pct * 100)}%`]].map(([label, value]) => <article key={label} className="bg-[#121212] p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-white/45">{label}</p><p className="mt-4 text-3xl font-black">{value}</p><p className="mt-2 text-xs text-white/40">{advanced.season} · {advanced.gp} GP</p></article>)}</section>}<div className="mt-5"><TrendChart seasons={trends} /></div><section className="mt-5 grid gap-5 md:grid-cols-2"><SimilarPlayers players={detail.similar_players} onSelect={onSelect} /><ContractCard contract={detail.contract} years={detail.contract_years} money={money} /></section>{detail.shooting_zones.length > 0 && <section className="mt-5 border border-white/10 bg-[#121212] p-6"><h2 className="text-sm font-black uppercase tracking-[0.12em]">Shooting zones</h2><div className="mt-5 grid gap-px bg-white/10 md:grid-cols-5">{detail.shooting_zones.slice(0, 5).map((zone) => <article key={zone.zone} className="bg-[#121212] p-4"><p className="text-[10px] text-white/45">{zone.zone}</p><p className="mt-3 text-2xl font-black">{(zone.fg_pct * 100).toFixed(1)}%</p><p className="mt-1 text-[10px] text-white/40">{zone.fgm}/{zone.fga} FG</p></article>)}</div></section>}<section className="mt-5 grid gap-5 md:grid-cols-2">{measure && <DataCard title="Draft combine measurements" data={measure} fields={["height_wo_shoes", "weight", "wingspan", "standing_reach", "body_fat_pct"]} />}{tests && <DataCard title="Draft combine testing" data={tests} fields={["standing_vertical", "max_vertical", "lane_agility", "three_quarter_sprint", "bench_press"]} />}</section></>; }
function SimilarPlayers({ players, onSelect }: { players: Detail["similar_players"]; onSelect: (slug: string) => void }) { return <article className="border border-white/10 bg-[#121212] p-6"><h2 className="text-sm font-black uppercase tracking-[0.12em]">Similar players</h2><p className="mt-2 text-xs text-white/45">Same-season advanced-profile similarity, normalized by league variation.</p><div className="mt-4 space-y-2">{players.map((p) => <button type="button" onClick={() => onSelect(p.slug)} key={p.slug} className="flex w-full items-center justify-between border-b border-white/10 pb-2 text-left text-sm hover:text-white/60"><span><b>{p.name}</b> <span className="text-white/45">· {p.team}</span></span><span className="text-xs text-white/45">{p.distance}</span></button>)}</div></article>; }
function ContractCard({ contract, years, money }: { contract: Detail["contract"]; years: Detail["contract_years"]; money: (value: number | null) => string }) { if (!contract) return <article className="border border-white/10 bg-[#121212] p-6"><h2 className="text-sm font-black uppercase tracking-[0.12em]">Contract</h2><p className="mt-4 text-sm text-white/55">No reviewed contract dataset is loaded. Import the versioned CSV to surface salary, option, and contract-type data.</p></article>; return <article className="border border-white/10 bg-[#121212] p-6"><h2 className="text-sm font-black uppercase tracking-[0.12em]">Contract</h2><p className="mt-3 text-sm font-bold">{contract.contract_type} · {money(contract.current_salary)} current salary</p><p className="mt-1 text-xs text-white/45">As of {contract.as_of_date} · {contract.source}</p><div className="mt-4 space-y-2 text-xs">{years.map((year) => <p key={year.season}>{year.season}: {money(year.salary)} {year.player_option ? "· Player option" : ""}{year.team_option ? "· Team option" : ""}{year.early_termination_option ? "· ETO" : ""}</p>)}</div></article>; }
function DataCard({ title, data, fields }: { title: string; data: Record<string, string | number | null>; fields: string[] }) { const label = (key: string) => key.replaceAll("_", " "); return <article className="border border-white/10 bg-[#121212] p-6"><h2 className="text-sm font-black uppercase tracking-[0.12em]">{title}</h2><dl className="mt-5 space-y-3">{fields.map((field) => <div key={field} className="flex justify-between border-b border-white/10 pb-2 text-sm"><dt className="capitalize text-white/45">{label(field)}</dt><dd className="font-bold">{data[field] ?? "—"}</dd></div>)}</dl></article>; }
